version: '3.8'

services:
  bms-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4002:4002"
    volumes:
      # Mount toàn bộ project để hot reload
      - .:/app
      # Prevent overwriting node_modules
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT_SERVICE=4002
    restart: unless-stopped
    container_name: bms-service
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
